nelmio_api_doc:
    documentation:
        info:
            title: Articles API
            description: Some simple Articles and comments API
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!(/doc$|/doc.json)).*
